"use client"

import { useState, useTransition } from "react"
import { QRCodeSVG } from "qrcode.react"
import { Clipboard, Download, ExternalLink, FileText, Link2, QrCode, Send, UserCheck } from "lucide-react"
import { toast } from "sonner"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { closeEventCheckinSession, createEventCheckinSession, createEventFollowUp, createEventGuestCrmProfile, deleteEventResource, issueEventAttendeeToken, manualCheckInEventParticipant, rotateEventPublicToken, saveEventResource, scheduleEventCommunication } from "@/lib/events/actions"
import { eventCommunicationTemplates, type EventReport, type EventResourceItem } from "@/lib/events/types"
import type { EventDetail } from "@/lib/operational/data"

function publicUrl(token: string | null) {
  return token ? `${window.location.origin}/eventos/publico/${token}` : ""
}

export function EventParticipantsPanel({ event, canEdit, canExport }: { event: EventDetail; canEdit: boolean; canExport: boolean }) {
  const [pending, startTransition] = useTransition()
  const [qrValue, setQrValue] = useState("")
  const [sessionQrValue, setSessionQrValue] = useState("")
  const [sessionToken, setSessionToken] = useState("")
  const [sessionExpires, setSessionExpires] = useState("")
  function run(action: () => Promise<{ ok: boolean; error?: string }>) {
    startTransition(async () => { const result = await action(); if (!result.ok) toast.error(result.error ?? "Operação não concluída"); else { toast.success("Operação concluída"); window.location.reload() } })
  }
  return <div className="space-y-4"><Card><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><div><CardTitle className="text-base">Participantes</CardTitle><CardDescription>Membros e visitantes no mesmo fluxo, sem expor esta lista na página pública.</CardDescription></div>{canExport && <Button variant="outline" onClick={() => { window.location.href = `/api/v1/events/${event.id}/participants/export` }}><Download className="mr-2 h-4 w-4" />Exportar XLS</Button>}</div></CardHeader><CardContent>{event.participants.length ? <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b text-left text-xs text-muted-foreground"><th className="p-3">Pessoa</th><th className="p-3">Tipo</th><th className="p-3">Contato</th><th className="p-3">Status</th><th className="p-3">Presença</th><th className="p-3">Ações</th></tr></thead><tbody>{event.participants.map((participant) => <tr key={`${participant.kind}-${participant.id}`} className="border-b last:border-0"><td className="p-3 font-medium">{participant.personName}</td><td className="p-3 text-muted-foreground">{participant.kind === "guest" ? "Visitante" : "Membro"}</td><td className="p-3 text-muted-foreground">{participant.personPhone || participant.personEmail || "Sem contato"}</td><td className="p-3"><Badge variant={participant.status === "going" ? "default" : participant.status === "waitlisted" ? "secondary" : "outline"}>{participant.status === "going" ? "Inscrito" : participant.status === "waitlisted" ? "Espera" : "Cancelado"}</Badge></td><td className="p-3">{participant.checkedIn ? <Badge>Presente</Badge> : <span className="text-muted-foreground">Pendente</span>}</td><td className="p-3"><div className="flex flex-wrap gap-2">{canEdit && participant.status === "going" && <><Button size="sm" variant="outline" disabled={pending} onClick={() => run(() => manualCheckInEventParticipant({ eventId: event.id, kind: participant.kind, attendeeId: participant.kind === "guest" ? participant.guestId! : participant.id }))}><UserCheck className="mr-1 h-3.5 w-3.5" />Manual</Button><Button size="sm" variant="outline" disabled={pending} onClick={() => startTransition(async () => { const result = await issueEventAttendeeToken({ eventId: event.id, kind: participant.kind, attendeeId: participant.kind === "guest" ? participant.guestId! : participant.id }); if (!result.ok) toast.error(result.error ?? "QR não criado"); else { const value = `${window.location.origin}/eventos/check-in/${result.token}`; setQrValue(value); toast.success("QR do participante criado") } })}><QrCode className="mr-1 h-3.5 w-3.5" />QR</Button></>}</div></td></tr>)}</tbody></table></div> : <p className="text-sm text-muted-foreground">Nenhuma inscrição registrada.</p>}</CardContent></Card>
    {event.participants.some((participant) => participant.kind === "guest" && participant.consented && !participant.personId) && <Card><CardHeader><CardTitle className="text-base">Visitantes e CRM</CardTitle><CardDescription>Vincule visitantes ao cadastro e abra acompanhamento somente após consentimento.</CardDescription></CardHeader><CardContent className="space-y-2">{event.participants.filter((participant) => participant.kind === "guest" && participant.consented && !participant.personId).map((participant) => <div key={participant.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border p-3 text-sm"><span>{participant.personName}</span><Button size="sm" variant="outline" disabled={pending} onClick={() => startTransition(async () => { const result = await createEventGuestCrmProfile({ eventId: event.id, guestId: participant.guestId! }); if (result.ok) { toast.success("Visitante vinculado ao CRM"); window.location.reload() } else toast.error(result.error ?? "Vínculo não criado") })}>Vincular ao CRM</Button></div>)}</CardContent></Card>}
    {qrValue && <Card><CardHeader><CardTitle className="text-base">QR do participante</CardTitle><CardDescription>Entregue este QR apenas à pessoa correspondente.</CardDescription></CardHeader><CardContent className="flex flex-wrap items-center gap-5"><QRCodeSVG value={qrValue} size={190} includeMargin /><div className="space-y-2 text-sm"><p className="break-all text-muted-foreground">{qrValue}</p><Button variant="outline" onClick={() => navigator.clipboard?.writeText(qrValue)}><Clipboard className="mr-2 h-4 w-4" />Copiar link</Button></div></CardContent></Card>}
    {canEdit && <Card><CardHeader><CardTitle className="text-base">Check-in do evento</CardTitle><CardDescription>Abra uma janela operacional antes de iniciar a conferência. O QR do evento aceita membro inscrito e visitante sem inscrição.</CardDescription></CardHeader><CardContent className="flex flex-wrap items-end gap-5"><Button disabled={pending} onClick={() => startTransition(async () => { const result = await createEventCheckinSession(event.id); if (!result.ok) toast.error(result.error ?? "Sessão não criada"); else { const value = `${window.location.origin}/eventos/check-in/sessao/${result.token}`; setSessionToken(result.token ?? ""); setSessionQrValue(value); setSessionExpires(result.expiresAt ?? ""); toast.success("Sessão de check-in aberta") } })}><QrCode className="mr-2 h-4 w-4" />Abrir check-in</Button>{sessionQrValue && <div className="rounded-lg border bg-white p-2"><QRCodeSVG value={sessionQrValue} size={150} includeMargin /></div>}{sessionToken && <div className="text-sm"><p className="font-medium">Sessão aberta</p><p className="text-muted-foreground">Expira em {new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(new Date(sessionExpires))}</p><p className="break-all text-xs text-muted-foreground">{sessionQrValue}</p><div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => navigator.clipboard?.writeText(sessionQrValue)}><Clipboard className="mr-2 h-4 w-4" />Copiar QR</Button><Button size="sm" variant="outline" onClick={() => startTransition(async () => { const result = await closeEventCheckinSession(event.id); if (result.ok) { setSessionToken(""); setSessionQrValue(""); toast.success("Sessão encerrada") } else toast.error(result.error ?? "Sessão não encerrada") })}>Encerrar</Button></div></div>}</CardContent></Card>}
  </div>
}

export function EventReportPanel({ event, report, canEdit }: { event: EventDetail; report: EventReport; canEdit: boolean }) {
  const [pending, startTransition] = useTransition()
  return <div className="space-y-4"><Card><CardHeader><CardTitle className="text-base">Indicadores do evento</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Inscritos", report.going], ["Presentes", report.present], ["Faltantes", report.absent], ["Visitantes presentes", report.guestPresent]].map(([label, value]) => <div key={String(label)} className="rounded-lg border p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>)}</CardContent></Card><Card><CardHeader><CardTitle className="text-base">Registros de presença</CardTitle></CardHeader><CardContent>{event.attendanceRecords.length ? <div className="divide-y rounded-lg border">{event.attendanceRecords.map((record) => <div key={record.id} className="flex flex-wrap items-center justify-between gap-3 p-3 text-sm"><div><p className="font-medium">{record.personName}</p><p className="text-xs text-muted-foreground">{record.occurredOn} {record.occurredTime || ""} · {record.registeredByName || "Registro operacional"} · {record.checkinSource === "qr" ? "QR" : "Manual"}</p></div><Badge variant={record.status === "present" ? "default" : "outline"}>{record.status === "present" ? "Presente" : record.status === "absent" ? "Ausente" : "Justificada"}</Badge></div>)}</div> : <p className="text-sm text-muted-foreground">Nenhum registro de presença vinculado a este evento.</p>}</CardContent></Card><Card><CardHeader><CardTitle className="text-base">Acompanhamento autorizado</CardTitle><CardDescription>Gere tarefa individual para faltantes inscritos, sem criar tarefa duplicada.</CardDescription></CardHeader><CardContent>{report.followUpCandidates.length ? <div className="divide-y rounded-lg border">{report.followUpCandidates.map((person) => <div key={person.id} className="flex flex-wrap items-center justify-between gap-3 p-3"><div><p className="font-medium">{person.name}</p><p className="text-xs text-muted-foreground">{person.phone || person.email || "Sem contato"}</p></div>{canEdit && <Button size="sm" variant="outline" disabled={pending} onClick={() => startTransition(async () => { const result = await createEventFollowUp({ eventId: event.id, personId: person.id }); if (result.ok) toast.success("Acompanhamento criado"); else toast.error(result.error ?? "Tarefa não criada") })}>Criar acompanhamento</Button>}</div>)}</div> : <p className="text-sm text-muted-foreground">Nenhum faltante identificado.</p>}</CardContent></Card></div>
}

export function EventCommunicationPanel({ event, canEdit }: { event: EventDetail; canEdit: boolean }) {
  const [pending, startTransition] = useTransition()
  const [templateKey, setTemplateKey] = useState("reminder_24h")
  const [channel, setChannel] = useState<"push" | "email" | "whatsapp">("whatsapp")
  const [audience, setAudience] = useState<"going" | "waitlist" | "guests" | "volunteers" | "ministry" | "public" | "all">("going")
  const [content, setContent] = useState("")
  const [scheduledAt, setScheduledAt] = useState("")
  const selectedTemplate = eventCommunicationTemplates.find((item) => item.key === templateKey)
  return <Card><CardHeader><CardTitle className="text-base">Comunicação agendada</CardTitle><CardDescription>Cria snapshot de destinatários e entrega pela fila com retry, sem prometer envio antes do status final.</CardDescription></CardHeader><CardContent>{canEdit ? <div className="grid gap-4 md:grid-cols-2"><div className="grid gap-2"><Label>Modelo</Label><Select value={templateKey} onValueChange={(value) => setTemplateKey(value ?? "reminder_24h")}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{eventCommunicationTemplates.map((item) => <SelectItem key={item.key} value={item.key}>{item.label}</SelectItem>)}</SelectContent></Select></div><div className="grid gap-2"><Label>Público</Label><Select value={audience} onValueChange={(value) => setAudience((value ?? "going") as typeof audience)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="going">Inscritos</SelectItem><SelectItem value="waitlist">Lista de espera</SelectItem><SelectItem value="guests">Visitantes</SelectItem><SelectItem value="volunteers">Voluntários</SelectItem><SelectItem value="ministry">Ministério ligado</SelectItem><SelectItem value="public">Público geral inscrito</SelectItem><SelectItem value="all">Todos os públicos</SelectItem></SelectContent></Select></div><div className="grid gap-2"><Label>Canal</Label><Select value={channel} onValueChange={(value) => setChannel((value ?? "whatsapp") as typeof channel)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="push">Push</SelectItem><SelectItem value="email">E-mail</SelectItem><SelectItem value="whatsapp">WhatsApp</SelectItem></SelectContent></Select></div><div className="grid gap-2"><Label>Enviar em (opcional)</Label><Input type="datetime-local" value={scheduledAt} onChange={(e) => setScheduledAt(e.target.value)} /></div><div className="grid gap-2 md:col-span-2"><Label>Texto</Label><Textarea value={content} onChange={(e) => setContent(e.target.value)} placeholder={selectedTemplate?.title ?? "Mensagem"} rows={4} /></div><Button className="md:col-span-2" disabled={pending} onClick={() => startTransition(async () => { const result = await scheduleEventCommunication({ eventId: event.id, templateKey, channel, audience, content: content || undefined, scheduledAt: scheduledAt ? new Date(scheduledAt).toISOString() : null }); if (result.ok) { toast.success(`${result.deliveryCount ?? 0} entrega(s) enfileirada(s)`); window.location.reload() } else toast.error(result.error ?? "Campanha não criada") })}><Send className="mr-2 h-4 w-4" />{pending ? "Agendando..." : "Agendar comunicação"}</Button></div> : <p className="text-sm text-muted-foreground">Sem permissão para agendar comunicação.</p>}</CardContent></Card>
}

export function EventResourcesPanel({ event, resources, canEdit, canDelete }: { event: EventDetail; resources: EventResourceItem[]; canEdit: boolean; canDelete: boolean }) {
  const [pending, startTransition] = useTransition()
  const [title, setTitle] = useState("")
  const [notes, setNotes] = useState("")
  const [externalUrl, setExternalUrl] = useState("")
  function save() { startTransition(async () => { const result = await saveEventResource({ eventId: event.id, title, notes, externalUrl }); if (result.ok) { toast.success("Recurso salvo"); setTitle(""); setNotes(""); setExternalUrl(""); window.location.reload() } else toast.error(result.error ?? "Recurso não salvo") }) }
  return <div className="space-y-4"><Card><CardHeader><CardTitle className="text-base">Arquivos e observações</CardTitle><CardDescription>Links e observações ficam vinculados ao tenant e ao evento.</CardDescription></CardHeader><CardContent className="space-y-4">{resources.length ? <div className="divide-y rounded-lg border">{resources.map((resource) => <div key={resource.id} className="flex flex-wrap items-start justify-between gap-3 p-3"><div><p className="font-medium">{resource.title}</p>{resource.notes && <p className="mt-1 whitespace-pre-wrap text-sm text-muted-foreground">{resource.notes}</p>}{resource.externalUrl && <a href={resource.externalUrl} target="_blank" rel="noreferrer" className="mt-1 inline-flex items-center text-sm text-primary underline"><ExternalLink className="mr-1 h-3.5 w-3.5" />Abrir link</a>}</div>{canDelete && <Button variant="ghost" size="sm" disabled={pending} onClick={() => startTransition(async () => { const result = await deleteEventResource({ eventId: event.id, resourceId: resource.id }); if (result.ok) { toast.success("Recurso removido"); window.location.reload() } else toast.error(result.error ?? "Recurso não removido") })}>Remover</Button>}</div>)}</div> : <p className="text-sm text-muted-foreground">Nenhum recurso cadastrado.</p>}{canEdit && <div className="grid gap-3 rounded-lg border p-4 md:grid-cols-2"><div className="grid gap-2"><Label>Título</Label><Input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Ex.: roteiro do evento" /></div><div className="grid gap-2"><Label>URL externa</Label><Input type="url" value={externalUrl} onChange={(e) => setExternalUrl(e.target.value)} placeholder="https://..." /></div><div className="grid gap-2 md:col-span-2"><Label>Observação</Label><Textarea value={notes} onChange={(e) => setNotes(e.target.value)} rows={3} /></div><Button className="md:col-span-2" disabled={pending || !title.trim()} onClick={save}><FileText className="mr-2 h-4 w-4" />Salvar recurso</Button></div>}</CardContent></Card></div>
}

export function EventPublicShare({ event, canEdit }: { event: EventDetail; canEdit: boolean }) {
  const [copied, setCopied] = useState(false)
  if (!event.publicToken) return <p className="text-sm text-muted-foreground">Link público ainda não disponível. A migration de eventos precisa estar aplicada.</p>
  const path = publicUrl(event.publicToken)
  return <div className="flex flex-wrap items-center gap-2 text-sm"><Button variant="outline" onClick={() => { navigator.clipboard?.writeText(path); setCopied(true); toast.success("Link copiado") }}><Link2 className="mr-2 h-4 w-4" />{copied ? "Copiado" : "Copiar link público"}</Button><Button render={<a href={path} target="_blank" rel="noreferrer" />} variant="ghost"><ExternalLink className="mr-2 h-4 w-4" />Abrir público</Button>{canEdit && <Button variant="ghost" onClick={() => { if (!window.confirm("Rotacionar link? O link atual deixará de funcionar.")) return; rotateEventPublicToken(event.id).then((result) => { if (result.ok) { toast.success("Link rotacionado"); window.location.reload() } else toast.error(result.error ?? "Não foi possível rotacionar") }) }}>Rotacionar link</Button>}</div>
}
