"use client"

import { FormEvent, useState, useTransition } from "react"
import { useRouter } from "next/navigation"
import { QRCodeSVG } from "qrcode.react"
import { toast } from "sonner"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { cancelEventParticipant, issueEventAttendeeToken, registerEventParticipant } from "@/lib/events/actions"
import type { EventDetail } from "@/lib/operational/data"

export function EventParticipantsPanel({ event, people, canEdit, canExport }: { event: EventDetail; people: { id: string; name: string }[]; canEdit: boolean; canExport: boolean }) {
  const router = useRouter()
  const [pending, startTransition] = useTransition()
  const [query, setQuery] = useState("")
  const [status, setStatus] = useState("")
  const [kind, setKind] = useState("guest")
  const [qr, setQr] = useState("")
  const [showForm, setShowForm] = useState(false)
  const participants = event.participants.filter(p => (!status || p.status === status) && `${p.personName} ${p.personEmail} ${p.personPhone}`.toLocaleLowerCase("pt-BR").includes(query.toLocaleLowerCase("pt-BR")))
  const labels = { going: "Confirmado", waitlisted: "Lista de espera", canceled: "Cancelado" }
  function register(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const data = new FormData(e.currentTarget); startTransition(async () => { const result = await registerEventParticipant({ eventId: event.id, personId: kind === "member" ? String(data.get("personId")) : undefined, fullName: kind === "guest" ? String(data.get("fullName")) : undefined, email: String(data.get("email") || ""), phone: String(data.get("phone") || ""), consent: data.get("consent") === "on" }); if (result.ok) { toast.success(result.status === "going" ? "Inscrição confirmada" : "Participante na lista de espera"); setShowForm(false); router.refresh() } else toast.error(result.error) }) }
  const exportQuery = new URLSearchParams({ query, status })
  return <div className="space-y-4"><Card><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><CardTitle>Inscrições</CardTitle><div className="flex gap-2">{canEdit && <Button onClick={() => setShowForm(!showForm)}>Adicionar participante</Button>}{canExport && <Button variant="outline" render={<a href={`/api/v1/events/${event.id}/participants/export?${exportQuery}`} />}>Exportar XLS</Button>}</div></div></CardHeader><CardContent className="space-y-4">
    {showForm && <form onSubmit={register} className="space-y-3 rounded-lg border p-4"><Label htmlFor="participant-kind">Tipo de participante</Label><select id="participant-kind" className="h-10 w-full rounded-md border bg-background px-3" value={kind} onChange={e => setKind(e.target.value)}><option value="guest">Visitante</option><option value="member">Pessoa cadastrada</option></select>{kind === "member" ? <><Label htmlFor="personId">Pessoa cadastrada</Label><select id="personId" name="personId" className="h-10 w-full rounded-md border bg-background px-3" required><option value="">Selecione uma pessoa</option>{people.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></> : <><Label htmlFor="fullName">Nome completo</Label><Input id="fullName" name="fullName" required minLength={2} /><Label htmlFor="email">E-mail</Label><Input id="email" name="email" type="email" /><Label htmlFor="phone">Telefone</Label><Input id="phone" name="phone" type="tel" /><label className="flex items-start gap-2 text-sm"><input name="consent" type="checkbox" required />O visitante autorizou o uso dos dados para esta inscrição.</label></>}<Button type="submit" disabled={pending}>Salvar inscrição</Button><p className="text-xs text-muted-foreground">Ao atingir a capacidade, novas inscrições entram na lista de espera.</p></form>}
    <div className="flex flex-wrap gap-3"><Input className="sm:max-w-sm" aria-label="Buscar inscrições" placeholder="Nome, e-mail ou telefone" value={query} onChange={e => setQuery(e.target.value)} /><select aria-label="Situação da inscrição" className="h-10 rounded-md border bg-background px-3" value={status} onChange={e => setStatus(e.target.value)}><option value="">Todas as situações</option>{Object.entries(labels).map(([key, value]) => <option key={key} value={key}>{value}</option>)}</select></div><p className="text-sm text-muted-foreground">{participants.length} participantes encontrados</p><div className="divide-y rounded-lg border">{participants.map(p => <div key={`${p.kind}-${p.id}`} className="flex flex-wrap items-center justify-between gap-3 p-3"><div><p className="text-sm font-medium">{p.personName}</p><p className="text-xs text-muted-foreground">{p.kind === "guest" ? "Visitante" : "Membro"} · {labels[p.status]} · {p.checkedIn ? "Presente" : "Sem presença registrada"}</p><p className="text-xs text-muted-foreground">{p.personEmail || p.personPhone}</p></div>{canEdit && <div className="flex flex-wrap gap-2">{p.status === "going" && <Button size="sm" variant="outline" disabled={pending} onClick={() => startTransition(async () => { const result = await issueEventAttendeeToken({ eventId: event.id, kind: p.kind, attendeeId: p.id }); if (result.ok) setQr(`${window.location.origin}/eventos/check-in/${result.token}`); else toast.error(result.error) })}>QR individual</Button>}{p.confirmationToken && <Button size="sm" variant="outline" render={<a href={`/eventos/inscricao/${p.confirmationToken}`} target="_blank" rel="noreferrer" />}>Comprovante</Button>}{p.status !== "canceled" && <Button size="sm" variant="outline" disabled={pending} onClick={() => startTransition(async () => { const result = await cancelEventParticipant({ eventId: event.id, kind: p.kind, attendeeId: p.id }); if (result.ok) { toast.success("Inscrição cancelada"); router.refresh() } else toast.error(result.error) })}>Cancelar inscrição</Button>}</div>}</div>)}{!participants.length && <p className="p-4 text-sm text-muted-foreground">Nenhuma inscrição encontrada.</p>}</div></CardContent></Card>{qr && <Card><CardHeader><CardTitle>QR individual do participante</CardTitle></CardHeader><CardContent className="flex flex-wrap items-center gap-5"><div className="bg-white p-3"><QRCodeSVG value={qr} size={180} /></div><Button variant="outline" onClick={() => navigator.clipboard.writeText(qr)}>Copiar link</Button><Button variant="ghost" onClick={() => setQr("")}>Fechar</Button></CardContent></Card>}</div>
}
