"use client"

import { useState, useTransition } from "react"
import { useConfirmAction } from "@/components/shared/use-confirm-action"
import { ExternalLink, FileText, Link2, Send } from "lucide-react"
import { toast } from "sonner"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { createEventFollowUp, deleteEventResource, rotateEventPublicToken, saveEventResource, scheduleEventCommunication } from "@/lib/events/actions"
import { eventCommunicationTemplates, type EventReport, type EventResourceItem } from "@/lib/events/types"
import type { EventDetail } from "@/lib/operational/data"

export function EventReportPanel({ event, report, canEdit }: { event: EventDetail; report: EventReport; canEdit: boolean }) {
  const [pending, startTransition] = useTransition()
  return <div className="space-y-4"><Card><CardHeader><CardTitle className="text-base">Indicadores do evento</CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Inscritos", report.going], ["Presentes", report.present], ["Faltantes", report.absent], ["Visitantes presentes", report.guestPresent]].map(([label, value]) => <div key={String(label)} className="rounded-lg border p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>)}</CardContent></Card><Card><CardHeader><CardTitle className="text-base">Registros de presença</CardTitle></CardHeader><CardContent>{event.attendanceRecords.length ? <div className="divide-y rounded-lg border">{event.attendanceRecords.map((record) => <div key={record.id} className="flex flex-wrap items-center justify-between gap-3 p-3 text-sm"><div><p className="font-medium">{record.personName}</p><p className="text-xs text-muted-foreground">{record.occurredOn.split("-").reverse().join("/")} {record.occurredTime?.slice(0, 5) || ""} · {record.registeredByName || "Registro operacional"} · {record.checkinSource === "qr" ? "QR" : "Manual"}</p></div><Badge variant={record.status === "present" ? "default" : "outline"}>{record.status === "present" ? "Presente" : record.status === "absent" ? "Ausente" : "Justificada"}</Badge></div>)}</div> : <p className="text-sm text-muted-foreground">Nenhum registro de presença vinculado a este evento.</p>}</CardContent></Card><Card><CardHeader><CardTitle className="text-base">Acompanhamento autorizado</CardTitle><CardDescription>Gere tarefa individual para faltantes inscritos, sem criar tarefa duplicada.</CardDescription></CardHeader><CardContent>{report.followUpCandidates.length ? <div className="divide-y rounded-lg border">{report.followUpCandidates.map((person) => <div key={person.id} className="flex flex-wrap items-center justify-between gap-3 p-3"><div><p className="font-medium">{person.name}</p><p className="text-xs text-muted-foreground">{person.phone || person.email || "Sem contato"}</p></div>{canEdit && <Button size="sm" variant="outline" disabled={pending} onClick={() => startTransition(async () => { const result = await createEventFollowUp({ eventId: event.id, personId: person.id }); if (result.ok) toast.success("Acompanhamento criado"); else toast.error(result.error ?? "Tarefa não criada") })}>Criar acompanhamento</Button>}</div>)}</div> : <p className="text-sm text-muted-foreground">Nenhum faltante identificado.</p>}</CardContent></Card></div>
}

export function EventCommunicationPanel({ event, canEdit }: { event: EventDetail; canEdit: boolean }) {
  const [pending, startTransition] = useTransition()
  const [templateKey, setTemplateKey] = useState("reminder_24h")
  const [channel, setChannel] = useState<"push" | "email" | "whatsapp">("whatsapp")
  const [audience, setAudience] = useState<"going" | "waitlist" | "guests" | "volunteers" | "ministry" | "public" | "all">("going")
  const [content, setContent] = useState("")
  const [scheduledAt, setScheduledAt] = useState("")
  const selectedTemplate = eventCommunicationTemplates.find((item) => item.key === templateKey)
  return <Card><CardHeader><CardTitle className="text-base">Comunicação agendada</CardTitle><CardDescription>Escolha o público e o canal. Acompanhe a situação dos envios no histórico.</CardDescription></CardHeader><CardContent>{canEdit ? <div className="grid gap-4 md:grid-cols-2"><div className="grid gap-2"><Label>Modelo</Label><Select value={templateKey} onValueChange={(value) => setTemplateKey(value ?? "reminder_24h")}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{eventCommunicationTemplates.map((item) => <SelectItem key={item.key} value={item.key}>{item.label}</SelectItem>)}</SelectContent></Select></div><div className="grid gap-2"><Label>Público</Label><Select value={audience} onValueChange={(value) => setAudience((value ?? "going") as typeof audience)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="going">Inscritos</SelectItem><SelectItem value="waitlist">Lista de espera</SelectItem><SelectItem value="guests">Visitantes</SelectItem><SelectItem value="volunteers">Voluntários</SelectItem><SelectItem value="ministry">Ministério ligado</SelectItem><SelectItem value="public">Público geral inscrito</SelectItem><SelectItem value="all">Todos os públicos</SelectItem></SelectContent></Select></div><div className="grid gap-2"><Label>Canal</Label><Select value={channel} onValueChange={(value) => setChannel((value ?? "whatsapp") as typeof channel)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="push">Push</SelectItem><SelectItem value="email">E-mail</SelectItem><SelectItem value="whatsapp">WhatsApp</SelectItem></SelectContent></Select></div><div className="grid gap-2"><Label>Enviar em (opcional)</Label><Input type="datetime-local" value={scheduledAt} onChange={(e) => setScheduledAt(e.target.value)} /></div><div className="grid gap-2 md:col-span-2"><Label>Texto</Label><Textarea value={content} onChange={(e) => setContent(e.target.value)} placeholder={selectedTemplate?.title ?? "Mensagem"} rows={4} /></div><Button className="md:col-span-2" disabled={pending} onClick={() => startTransition(async () => { const result = await scheduleEventCommunication({ eventId: event.id, templateKey, channel, audience, content: content || undefined, scheduledAt: scheduledAt ? new Date(scheduledAt).toISOString() : null }); if (result.ok) { toast.success(`${result.deliveryCount ?? 0} entrega(s) enfileirada(s)`); window.location.reload() } else toast.error(result.error ?? "Campanha não criada") })}><Send className="mr-2 h-4 w-4" />{pending ? "Agendando..." : "Agendar comunicação"}</Button></div> : <p className="text-sm text-muted-foreground">Sem permissão para agendar comunicação.</p>}</CardContent></Card>
}

export function EventResourcesPanel({ event, resources, canEdit, canDelete }: { event: EventDetail; resources: EventResourceItem[]; canEdit: boolean; canDelete: boolean }) {
  const [pending, startTransition] = useTransition()
  const [title, setTitle] = useState("")
  const [notes, setNotes] = useState("")
  const [externalUrl, setExternalUrl] = useState("")
  function save() { startTransition(async () => { const result = await saveEventResource({ eventId: event.id, title, notes, externalUrl }); if (result.ok) { toast.success("Recurso salvo"); setTitle(""); setNotes(""); setExternalUrl(""); window.location.reload() } else toast.error(result.error ?? "Recurso não salvo") }) }
  return <div className="space-y-4"><Card><CardHeader><CardTitle className="text-base">Arquivos e observações</CardTitle><CardDescription>Reúna os materiais e as orientações deste evento.</CardDescription></CardHeader><CardContent className="space-y-4">{resources.length ? <div className="divide-y rounded-lg border">{resources.map((resource) => <div key={resource.id} className="flex flex-wrap items-start justify-between gap-3 p-3"><div><p className="font-medium">{resource.title}</p>{resource.notes && <p className="mt-1 whitespace-pre-wrap text-sm text-muted-foreground">{resource.notes}</p>}{resource.externalUrl && <a href={resource.externalUrl} target="_blank" rel="noreferrer" className="mt-1 inline-flex items-center text-sm text-primary underline"><ExternalLink className="mr-1 h-3.5 w-3.5" />Abrir link</a>}</div>{canDelete && <Button variant="ghost" size="sm" disabled={pending} onClick={() => startTransition(async () => { const result = await deleteEventResource({ eventId: event.id, resourceId: resource.id }); if (result.ok) { toast.success("Recurso removido"); window.location.reload() } else toast.error(result.error ?? "Recurso não removido") })}>Remover</Button>}</div>)}</div> : <p className="text-sm text-muted-foreground">Nenhum recurso cadastrado.</p>}{canEdit && <div className="grid gap-3 rounded-lg border p-4 md:grid-cols-2"><div className="grid gap-2"><Label>Título</Label><Input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Ex.: roteiro do evento" /></div><div className="grid gap-2"><Label>URL externa</Label><Input type="url" value={externalUrl} onChange={(e) => setExternalUrl(e.target.value)} placeholder="https://..." /></div><div className="grid gap-2 md:col-span-2"><Label>Observação</Label><Textarea value={notes} onChange={(e) => setNotes(e.target.value)} rows={3} /></div><Button className="md:col-span-2" disabled={pending || !title.trim()} onClick={save}><FileText className="mr-2 h-4 w-4" />Salvar recurso</Button></div>}</CardContent></Card></div>
}

export function EventPublicShare({ event, canEdit }: { event: EventDetail; canEdit: boolean }) {
  const [copied, setCopied] = useState(false)
  const confirmRotate = useConfirmAction()
  if (!event.publicToken) return <p className="text-sm text-muted-foreground">Link público ainda não disponível.</p>
  const path = event.publicPath || ""
  return <div className="flex flex-wrap items-center gap-2 text-sm"><Button variant="outline" onClick={() => { navigator.clipboard?.writeText(new URL(path, window.location.origin).href); setCopied(true); toast.success("Link copiado") }}><Link2 className="mr-2 h-4 w-4" />{copied ? "Copiado" : "Copiar link público"}</Button><Button render={<a href={path} target="_blank" rel="noreferrer" />} variant="ghost"><ExternalLink className="mr-2 h-4 w-4" />Abrir público</Button>{canEdit && <Button variant="ghost" onClick={() => confirmRotate.confirm({ title: "Rotacionar link", message: "Rotacionar link? O link atual deixará de funcionar.", confirmLabel: "Rotacionar", action: () => rotateEventPublicToken(event.id).then((result) => { if (result.ok) { toast.success("Link rotacionado"); window.location.reload() } else toast.error(result.error ?? "Não foi possível rotacionar") }) })}>Rotacionar link</Button>}{confirmRotate.dialog()}</div>
}
