import { expect, test } from "@playwright/test"
import { gotoAuthenticated } from "./helpers/auth"
import { e2eRunPrefix, readE2EAccounts } from "./helpers/accounts"

const e2e = readE2EAccounts()
test.use({ storageState: "playwright/.auth/admin.json", timezoneId: "America/Sao_Paulo" })

test("follow-up explains rules and exposes the complete configuration", async ({ page }) => {
  await gotoAuthenticated(page, e2e.accounts.admin, "/configuracoes/follow-up")
  await page.waitForLoadState("networkidle")
  await expect(page.getByRole("heading", { name: "Regras de follow-up" })).toBeVisible()
  await expect(page.getByText("Como começar", { exact: true })).toBeVisible()
  const visitor = page.locator('[data-slot="card"]').filter({ hasText: "Novo visitante cadastrado" })
  await visitor.getByRole("button", { name: /Configurar regra|Editar regra/ }).click()
  const dialog = page.getByRole("dialog")
  await expect(dialog.getByText("Responsável Padrão", { exact: true })).toBeVisible()
  await expect(dialog.getByText("Considerar registros dos últimos (dias)", { exact: true })).toBeVisible()
  const days = dialog.locator('input[type="number"]')
  await days.nth(1).fill("0")
  await days.first().fill("0")
  await dialog.getByRole("button", { name: "Salvar Configuração" }).click()
  await expect(page.getByText(/Revise os dias/)).toBeVisible()
  await dialog.getByRole("button", { name: "Cancelar", exact: true }).click()
  const cell = page.locator('[data-slot="card"]').filter({ hasText: "Pessoa sem célula ativa" })
  await cell.getByRole("button", { name: /Configurar regra|Editar regra/ }).click()
  await expect(page.getByRole("dialog").locator('input[type="number"]')).toHaveCount(1)
})

test("the journey link opens its configuration tab directly", async ({ page }) => {
  await gotoAuthenticated(page, e2e.accounts.admin, "/pessoas?tab=config#trilhas")
  await page.waitForLoadState("networkidle")
  await expect(page.getByRole("tab", { name: "Atividades & Parâmetros" })).toHaveAttribute("aria-selected", "true")
  await expect(page.locator("#trilhas")).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test("configure, enroll, complete a journey and create a follow-up with the correct deadline", async ({ page }) => {
  test.setTimeout(120_000)
  expect(e2e.accounts.admin.email).toMatch(/@altar-church\.test$/)
  const name = e2eRunPrefix("journey")
  await gotoAuthenticated(page, e2e.accounts.admin, "/pessoas?tab=config#trilhas")
  await page.waitForLoadState("networkidle")
  await page.getByRole("button", { name: "Nova trilha", exact: true }).click()
  const dialog = page.getByRole("dialog")
  await dialog.locator("input").first().fill(name)
  await dialog.getByRole("button", { name: "Criar e adicionar etapas" }).click()
  const builder = page.getByRole("dialog")
  await expect(builder.getByRole("heading", { name: "Construtor de Trilha" })).toBeVisible()
  try {
    for (const step of ["Primeiro contato", "Discipulado"]) {
      await builder.getByRole("button", { name: "Adicionar Etapa", exact: true }).click()
      await builder.getByPlaceholder("Ex.: 1. Ligação de Boas-Vindas ou Batismo").fill(step)
      await builder.getByRole("button", { name: "Salvar Etapa", exact: true }).click()
      await expect(builder.getByText(step, { exact: true })).toBeVisible()
    }
    await builder.getByTitle("Editar etapa").nth(1).click()
    await builder.getByPlaceholder("Ex.: 1. Ligação de Boas-Vindas ou Batismo").fill("Discipulado atualizado")
    await builder.getByRole("button", { name: "Salvar Etapa", exact: true }).click()
    await expect(builder.getByText("Discipulado atualizado", { exact: true })).toBeVisible()
    await page.keyboard.press("Escape")
    await page.reload()
    const card = page.locator("#trilhas .grid > div").filter({ hasText: name })
    await card.getByRole("button", { name: "Editar trilha e etapas" }).click()
    await expect(page.getByRole("dialog").getByTitle("Editar etapa")).toHaveCount(2)
    const names = await page.getByRole("dialog").locator("p.font-semibold, p.font-semibold.text-xs, p.text-xs.font-semibold").allTextContents()
    expect(names.filter((text) => /Primeiro contato|Discipulado atualizado/.test(text))).toEqual(["Primeiro contato", "Discipulado atualizado"])
    await page.keyboard.press("Escape")

    await page.goto(`/pessoas?search=${encodeURIComponent(e2e.accounts.member.name)}`)
    await page.waitForLoadState("networkidle")
    await page.getByRole("link", { name: e2e.accounts.member.name, exact: true }).first().click()
    await page.waitForLoadState("networkidle")
    await page.getByRole("tab", { name: "Jornada", exact: true }).click()
    await page.getByRole("button", { name: /Iniciar nova trilha|Iniciar primeira trilha/ }).first().click()
    await page.getByRole("dialog").getByRole("combobox").click()
    await page.getByRole("option", { name, exact: true }).click()
    await page.getByRole("dialog").getByRole("button", { name: "Iniciar Trilha", exact: true }).click()
    const enrollment = page.locator('[data-slot="card"]').filter({ hasText: name })
    await expect(enrollment.getByText(name, { exact: true })).toBeVisible()
    for (const count of [1, 2]) {
      await enrollment.getByRole("button", { name: "Concluir etapa", exact: true }).first().click()
      await page.getByRole("dialog").getByRole("button", { name: "Salvar etapa", exact: true }).click()
      await expect(enrollment.getByRole("button", { name: "Editar conclusão", exact: true })).toHaveCount(count)
    }
    await expect(enrollment.getByText("Concluída", { exact: true })).toBeVisible()
    await enrollment.getByRole("button", { name: "Encerrar trilha", exact: true }).click()
    await expect(enrollment.getByText("Encerrada", { exact: true })).toBeVisible()

    await page.getByRole("tab", { name: "Linha do tempo", exact: true }).click()
    await page.getByLabel("Título da tarefa *", { exact: true }).fill(name)
    await page.getByLabel("Prazo", { exact: true }).fill("2026-10-06T10:00")
    await page.getByRole("button", { name: "Criar tarefa", exact: true }).click()
    const task = page.locator("form").filter({ hasText: name })
    await expect(task.getByText(name, { exact: true })).toBeVisible()
    await expect(task.locator('input[name="dueAt"]')).toHaveValue("2026-10-06T10:00")
    await task.locator('select[name="status"]').selectOption("completed")
    await task.getByRole("button", { name: "Atualizar tarefa", exact: true }).click()
    await expect(task.locator('[data-slot="badge"]').filter({ hasText: "Concluída" })).toBeVisible()
    await expect(task.locator('input[name="dueAt"]')).toHaveValue("2026-10-06T10:00")
    await task.locator('select[name="status"]').selectOption("canceled")
    await task.getByRole("button", { name: "Atualizar tarefa", exact: true }).click()
    await expect(task.locator('[data-slot="badge"]').filter({ hasText: "Cancelada" })).toBeVisible()
  } finally {
    await page.goto("/pessoas?tab=config#trilhas")
    const card = page.locator("#trilhas .grid > div").filter({ hasText: name })
    await card.getByRole("button").first().click()
    await page.getByRole("menuitem", { name: "Excluir", exact: true }).click()
    await page.getByRole("alertdialog").getByRole("button", { name: /Excluir/ }).click()
    await expect(page.locator("#trilhas").getByText(name, { exact: true })).toHaveCount(0)
  }
})
